routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@getLandingPage')->name('home');

Auth::routes(['verify' => true]);

Route::group([], function () {
    Route::get('sign_up', 'WebsiteController@sign_up');
    Route::get('site/contactus', 'WebsiteController@contactus');
    Route::get('site/{page}', 'WebsiteController@site');
    Route::post('contact/send_message', 'WebsiteController@send_message');

    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
    Route::match(['get', 'post'], 'register/client_signup', '\App\Http\Controllers\Auth\RegisterController@client_signup');

    Route::group(['middleware' => ['auth', 'verified']], function () {
        Route::get('/dashboard', 'DashboardController@index');

        //Profile Controller
        Route::get('profile/edit', 'ProfileController@edit');
        Route::post('profile/update', 'ProfileController@update');
        Route::get('profile/change_password', 'ProfileController@change_password');
        Route::post('profile/update_password', 'ProfileController@update_password');

        //Membertship Controller
        Route::get('membership/my_subscription', 'MembershipController@my_subscription');  //View Subscription Details
        Route::get('membership/extend', 'MembershipController@extend');

        //Select Payment Gateway
        Route::post('membership/pay', 'MembershipController@pay');

        //Payment Gateway PayPal
        Route::get('membership/paypal/{action?}', 'MembershipController@paypal');

        //Payment Gateway Stripe
        Route::get('membership/stripe_payment/{action}/{payment_id?}', 'MembershipController@stripe_payment');

        //Payment Gateway RazorPay
        Route::post('membership/razorpay_payment/{payment_id}', 'MembershipController@razorpay_payment');

        //Paystack Payment Gateway
        Route::get('membership/paystack_payment/{payment_id}/{reference}', 'MembershipController@paystack_payment');

        /** Admin Only Route **/
        Route::group(['middleware' => ['admin']], function () {
            //User Controller
            Route::get('users/type/{user_type}', 'UserController@index');
            Route::resource('users', 'UserController');

            //Payment Controller
            Route::get('offline_payment/create', 'PaymentController@create_offline_payment');
            Route::post('offline_payment/store', 'PaymentController@store_offline_payment');
            Route::get('members/payment_history', 'PaymentController@payment_history');

            //Feature Controller
            Route::resource('features', 'FeatureController');

            //FAQ Controller
            Route::resource('faqs', 'FaqController');

            //Package Controller
            Route::resource('packages', 'PackageController');

            //Language Controller
            Route::resource('languages', 'LanguageController');

            //Utility Controller
            Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings');
            Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');
            Route::post('administration/upload_logo', 'UtilityController@upload_logo');
            Route::match(['get', 'patch'], 'administration/currency_rates/{id?}', 'UtilityController@currency_rates');
            Route::get('administration/backup_database', 'UtilityController@backup_database');

            //Theme Option
            Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');

            //Email Template
            Route::resource('email_templates', 'EmailTemplateController')->only([
                'index', 'show', 'edit', 'update',
            ]);
        });

        Route::group(['middleware' => ['company']], function () {
            //Project Controller
            Route::post('projects/get_table_data', 'ProjectController@get_table_data');
            Route::resource('projects', 'ProjectController');

            //Builder
            Route::resource('project/builder', 'BuilderController');
            Route::get('updateproject/builder/{id}', 'BuilderController@index');
            Route::get('project/larabuilder', 'BuilderController@larabuilder');
            Route::get('builder/novi', 'BuilderController@novi');
            Route::get('builder/lara', 'BuilderController@lara');
            Route::match(['get', 'post'], 'api/ajax', 'BuilderController@ajax');
            Route::get('test/backend/assets/builder', 'BuilderController@empty');

            Route::post('/img/remove', 'ProjectController@imgRemove')->name('delete.image');
            Route::post('/video/remove', 'ProjectController@videoRemove')->name('delete.video');

            //Payment Method
            Route::resource('payment_methods', 'PaymentMethodController');

            //Staff Controller
            Route::resource('staffs', 'StaffController');

            //User Roles
            Route::resource('roles', 'RoleController');

            //File Manager Controller
            Route::get('file_manager/directory/{parent_id}', 'FileManagerController@index')->name('file_manager.index');
            Route::get('file_manager/create_folder/{parent_id?}', 'FileManagerController@create_folder')->name('file_manager.create_folder');
            Route::post('file_manager/store_folder', 'FileManagerController@store_folder')->name('file_manager.create_folder');
            Route::get('file_manager/edit_folder/{id}', 'FileManagerController@edit_folder')->name('file_manager.edit_folder');
            Route::patch('file_manager/update_folder/{id}', 'FileManagerController@update_folder')->name('file_manager.edit_folder');
            Route::get('file_manager/create/{parent_id?}', 'FileManagerController@create')->name('file_manager.create');
            Route::resource('file_manager', 'FileManagerController');

            //Company Settings Controller
            Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
            Route::match(['get', 'post'], 'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');

            Route::match(['get', 'post'], 'company/crm_settings', 'CompanySettingsController@crm_settings')->name('company.crm_settings');

            //Company Email Template
            Route::get('company_email_template/get_template/{id}', 'CompanyEmailTemplateController@get_template');
            Route::resource('company_email_template', 'CompanyEmailTemplateController');

            //Permission Controller
            Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
            Route::post('permission/store', 'PermissionController@store')->name('permission.manage');
        });

        Route::group(['middleware' => ['client']], function () {
            //Projects
            Route::get('client/projects', 'ClientController@projects');
            Route::get('client/projects/{id}', 'ClientController@view_project');
        });
    });

    //Convert Currency
    Route::get('convert_currency/{from}/{to}/{amount}', 'AccountController@convert_currency');

    //Get Client Info
    Route::get('contacts/get_client_info/{id}', 'ContactController@get_client_info');

    //Get Client Info
    Route::get('projects/get_project_info/{id}', 'ProjectController@get_project_info');

    //View Invoice & Quotation without login
    Route::get('client/view_invoice/{id}', 'ClientController@view_invoice');

    //Online Invoice Payment
    Route::get('client/invoice_payment/{id}/{payment_method}', 'ClientController@invoice_payment');

    //Stripe Payment Gateway
    Route::get('client/stripe_payment/{action}/{invoice_id}', 'ClientController@stripe_payment');

    //PayPal Payment Gateway
    Route::get('client/paypal/{action?}/{invoice_id?}', 'ClientController@paypal');

    //Payment Gateway RazorPay
    Route::post('client/razorpay_payment/{invoice_id}', 'ClientController@razorpay_payment');

    //Paystack Payment Gateway
    Route::get('client/paystack_payment/{invoice_id}/{reference}', 'ClientController@paystack_payment');

    //Invoice & Quotation PDF Download
    Route::get('invoices/download_pdf/{id}', 'ClientController@download_invoice_pdf');
});

//Ajax Select2 Controller
Route::get('ajax/get_table_data', 'Select2Controller@get_table_data');

Route::post('createProject', 'ApiController@createProject');
Route::post('updateProject/{id}', 'ApiController@updateProject');

//Show Notification
Route::get('notification/{id}', 'NotificationController@show')->middleware('auth');

//Google Login
Route::get('google/redirect', 'Auth\SocialAuthGoogleController@redirect');
Route::get('google/callback', 'Auth\SocialAuthGoogleController@callback');

//PayPal IPN for Membership Payment
Route::post('membership/paypal_ipn', 'MembershipController@paypal_ipn');

//PayPal IPN for Invoice Payment
Route::post('client/paypal_ipn', 'ClientController@paypal_ipn');

Route::get('console/run', 'CronJobsController@run');

app/ActivityLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ActivityLog extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'activity_logs';

    public function created_by(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\User::class, 'user_id')->withDefault();
    }

    public function getCreatedAtAttribute($date): string
    {
        $date_format = get_company_option('date_format', 'Y-m-d');
        $time_format = get_company_option('time_format', 24) == '24' ? 'H:i' : 'h:i A';

        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format("$date_format $time_format");
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\DBNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_type', 'status', 'profile_picture',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function client(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany('App\Contact', 'user_id');
    }

    public function company(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Company::class, 'company_id')->withDefault();
    }

    public function role(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Role::class, 'role_id')->withDefault();
    }

    public function chat_groups(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany('App\ChatGroup', 'chat_group_users', 'user_id', 'group_id');
    }

    public function projects()
    {
        return $this->belongsToMany(\App\Project::class, 'project_members', 'user_id', 'project_id')->orderBy('id', 'desc');
    }

    public function tasks()
    {
        return $this->hasMany('App\Task', 'assigned_user_id')->orderBy('id', 'desc');
    }

    public function notifications()
    {
        return $this->morphMany(DBNotification::class, 'notifiable')
                            ->orderBy('created_at', 'desc');
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">

			<div class="card-body">
				<h4 class="d-none panel-title">{{ _lang('Create User') }}</h4>
				<form method="post" class="validate" autocomplete="off" action="{{url('users')}}" enctype="multipart/form-data">
				    <div class="row">
						<div class="col-md-6">
							  {{ csrf_field() }}
							  
							  <div class="form-group">
								<label class="control-label">{{ _lang('Business Name') }}</label>						
								<input type="text" class="form-control" name="business_name" value="{{ old('business_name') }}" required>
							  </div>
							  
							  <div class="form-group">
								<label class="control-label">{{ _lang('Name') }}</label>						
								<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
							  </div>

							  <div class="form-group">
								<label class="control-label">{{ _lang('Email') }}</label>						
								<input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
							  </div>

							  <div class="form-group">
								<label class="control-label">{{ _lang('Password') }}</label>						
								<input type="password" class="form-control" name="password" value="{{ old('password') }}" required>
							  </div>
							
							  <div class="form-group">
								<label class="control-label">{{ _lang('Confirm Password') }}</label>						
								<input type="password" class="form-control" name="password_confirmation" required>
							  </div>				  
							  
							  <div class="form-group">
									<label class="control-label">{{ _lang('Status') }}</label>						
									<select class="form-control select2" id="status" name="status" required>
									  <option value="1">{{ _lang('Active') }}</option>
									  <option value="0">{{ _lang('Inactive') }}</option>
									</select>
							  </div>
							  

							  <div class="form-group">
								<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
								<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
							  </div>
							
						</div>
						
						@php $free = DB::table('packages')->where('type', 'free')->first(); @endphp
						<div class="col-md-6">	

		                      <div class="col-md-12">
								  <div class="form-group">
									<label class="control-label">{{ _lang('Package') }}</label>						
									<select id="package" class="form-control" name="package_id" required>
										<option value="">{{ _lang('Select Package') }}</option>
										 @if(isset($free) && $free != '')
                                            <option type="{{$free->type}}" value="{{$free->id}}">{{$free->package_name}}</option>
                                        @endif
										{{ create_option('packages','id','package_name',old('package_id')) }}
									</select>
								  </div>
							  </div>
							  
							  <div class="col-md-12">
								  <div id="packageType" class="form-group">
									<label class="control-label">{{ _lang('Package Type') }}</label>						
									<select class="form-control auto-select" data-selected="{{ old('package_type') }}" id="package_type" name="package_type" required>
										<option value="">{{ _lang('Select Package') }}</option>
										<option value="monthly">{{ _lang('Monthly') }}</option>
										<option value="yearly">{{ _lang('Yearly') }}</option>
									</select>
								  </div>
							  </div>
							  
							  <div class="col-md-12">
								  <div id="membershipType" class="form-group">
									  <label class="control-label">{{ _lang('Membership Type') }}</label>						
									  <select class="form-control select2 auto-select" data-selected="{{ old('membership_type','trial') }}" name="membership_type" id="membership_type" required>
										  <option value="trial">{{ _lang('Trial') }}</option>
										  <option value="member">{{ _lang('Paid Member') }}</option>
									  </select>
								  </div>
							  </div>
							  
		  
							  <div class="col-md-12">
								 <div class="form-group">
									<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
									<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="">
								 </div>
							  </div>
						</div>
		            </div>			
				</form>
			</div>
	   </div>
	</div>
</div>
@endsection

@section('js-script')

<script>

	const select = document.getElementById('package');

select.addEventListener('change', function handleChange(event) {
	if( select.options[select.selectedIndex].getAttribute('type') == 'free') {
        $('#packageType').removeClass('d-block');
        $('#packageType').addClass('d-none');
        $('#package_type').removeAttr('required');
        $('#package_type').attr('disabled', 'disabled');

		$('#membershipType').removeClass('d-block');
        $('#membershipType').addClass('d-none');
        $('#membership_type').removeAttr('required');
        $('#membership_type').attr('disabled', 'disabled');
    
    } else {
        $('#packageType').removeClass('d-none');
        $('#packageType').addClass('d-block');
        $('#package_type').attr('required', 'required');
        $('#package_type').removeAttr('disabled');

		$('#membershipType').removeClass('d-none');
        $('#membershipType').addClass('d-block');
        $('#membership_type').attr('required', 'required');
        $('#membership_type').removeAttr('disabled');
    }
    });
</script>

@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
			<h4 class="d-none panel-title">{{ _lang('Update User') }}</h4>
			<form method="post" class="validate" autocomplete="off" action="{{ action('UserController@update', $id) }}" enctype="multipart/form-data">
				<div class="row">
					<div class="col-md-6">
						{{ csrf_field()}}
						<input name="_method" type="hidden" value="PATCH">
						 <div class="form-group">
							<label class="control-label">{{ _lang('Business Name') }}</label>
							<input type="text" class="form-control" name="business_name" value="{{ $user->company->business_name }}" required>
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Name') }}</label>
							<input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Email') }}</label>
							<input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Password') }}</label>
							<input type="password" class="form-control" name="password" value="">
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Confirm Password') }}</label>
							<input type="password" class="form-control" name="password_confirmation" value="">
						 </div>


						  <div class="form-group">
							<label class="control-label">{{ _lang('Status') }}</label>
							<select class="form-control select2 auto-select" data-selected="{{ $user->company->status }}" id="status" name="status" required>
							  <option value="1">{{ _lang('Active') }}</option>
							  <option value="0">{{ _lang('Inactive') }}</option>
							</select>
						  </div>


						  <div class="form-group">
							<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
						  </div>
					</div>

					<div class="col-md-6">

						<div class="form-group">
							<label class="control-label">{{ _lang('Package') }} ({{ _lang('Package will be reset if you change package') }})</label>
							<select class="form-control select2 auto-select" data-selected="{{ $user->company->package_id }}" id="package_id" name="package_id" required>
								<option value="">{{ _lang('Select Package') }}</option>
								{{ create_option('packages','id','package_name') }}
							</select>
						</div>

						<div class="form-group">
							<label class="control-label">{{ _lang('Package Type') }}</label>
							<select class="form-control auto-select" data-selected="{{ $user->company->package_type }}" id="package_type" name="package_type" required>
								<option value="monthly">{{ _lang('Monthly') }}</option>
								<option value="yearly">{{ _lang('Yearly') }}</option>
							</select>
						</div>

						<div class="form-group">
							 <label class="control-label">{{ _lang('Membership Type') }}</label>
							 <select class="form-control select2 auto-select" data-selected="{{ $user->company->membership_type }}" name="membership_type" id="membership_type" required>
							   <option value="trial">{{ _lang('Trial') }}</option>
							   <option value="member">{{ _lang('Paid Member') }}</option>
							 </select>
						</div>

						<div class="form-group">
							<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>
							<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{ $user->profile_picture != "" ? asset('/uploads/profile/'.$user->profile_picture) : '' }}" >
						</div>
					</div>
                </div>
			</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-12">
	    <a class="btn btn-primary btn-xs ajax-modal" data-title="{{ _lang('Add User') }}" href="{{ route('users.create') }}"><i class="ti-plus"></i> {{ _lang('Add New') }}</a>
		<div class="card mt-2">
			<div class="card-body">
				<h4 class="mt-0 header-title d-none panel-title">{{ $title }}</h4>
				<table class="table table-bordered data-table">
					<thead>
					  <tr>
						<th>{{ _lang('ID') }}</th>
						<th class="text-center">{{ _lang('Avatar') }}</th>
						<th>{{ _lang('Business Name') }}</th>
						<th>{{ _lang('Email') }}</th>
						<th>{{ _lang('Package') }}</th>
						<th class="text-center">{{ _lang('Membership') }}</th>
						<th>{{ _lang('Status') }}</th>
						<th class="text-center">{{ _lang('Action') }}</th>
					  </tr>
					</thead>
					<tbody>

					  @foreach($users as $user)
						<tr id="row_{{ $user->id }}">
							<td class='id'>{{ $user->id }}</td>
							<td class="text-center">
								<img src="{{ asset('/uploads/profile/'.$user->profile_picture) }}" class="thumb-sm rounded-circle mr-2">
							</td>
							<td class='name'>{{ $user->company->business_name }}</td>
							<td class='email'>{{ $user->email }}</td>
							@if($user->company->package->type == 'free')
							<td class='package_id'>{!! status($user->company->package->package_name, 'success') !!}</td>
							@else
							<td class='package_id'>{{ $user->company->package->package_name }}({{ ucwords($user->company->package_type) }})</td>
							@endif
							<td class='membership_type text-center'>{!! $user->company->membership_type == 'trial' ? clean(status(ucwords($user->company->membership_type), 'danger')) : clean(status(ucwords($user->company->membership_type), 'success')) !!}</td>
							<td class='status'>{!! $user->company->status == 1 ? clean(status(_lang('Active'), 'success')) : clean(status(_lang('In-Active'), 'danger')) !!}</td>
							<td class="text-center">
							  <form action="{{ action('UserController@destroy', $user['id']) }}" method="post">
								<a href="{{ action('UserController@edit', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="btn btn-outline-warning btn-xs ajax-modal">{{ _lang('Edit') }}</a>
								<a href="{{ action('UserController@show', $user['id']) }}" data-title="{{ _lang('View User') }}" class="btn btn-outline-primary btn-xs ajax-modal">{{ _lang('View') }}</a>
								{{ csrf_field() }}
								<input name="_method" type="hidden" value="DELETE">
								<button class="btn btn-outline-danger btn-xs btn-remove" type="submit">{{ _lang('Delete') }}</button>
							  </form>
							</td>
						</tr>
					  @endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/payments.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-12">
		<div class="card">
			<span class="panel-title d-none">{{ _lang('Payment History') }}</span>
			<div class="card-body">
			  <table class="table table-bordered data-table">
				<thead>
					<tr>
						<th>{{ _lang('Date') }}</th>
						<th>{{ _lang('Company') }}</th>
						<th>{{ _lang('Package') }}</th>
						<th>{{ _lang('Method') }}</th>
						<th class="text-right">{{ _lang('Amount') }}</th>
					</tr>
				</thead>
				<tbody>

				  @php $date_format = get_option('date_format','Y-m-d'); @endphp
				  @php $time_format = get_option('time_format',24) == '24' ? 'H:i' : 'h:i A'; @endphp
				  
				  @foreach($payment_history as $history)
					<tr>
						<td>{{ date("$date_format $time_format",strtotime($history->created_at)) }}</td>
						<td>{{ $history->company->business_name }}</td>
						<td>{{ $history->title }}</td>
						<td>{{ $history->method }}</td>					
						<td class="text-right"><b>{{ decimalPlace($history->amount, currency($history->currency)) }}</b></td>			
					</tr>
				  @endforeach
				</tbody>
			  </table>
			  
			  <div class="pull-right">
				 {{ $payment_history->links() }}
			  </div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
	<div class="card">
	<div class="card-body">
	  <h4 class="d-none panel-title">{{ _lang('View User') }}</h4>

	   @php $date_format = get_option('date_format','Y-m-d'); @endphp

	   <table class="table table-bordered">
			<tr><td colspan="2" class="text-center"><img class="thumb-xl rounded" src="{{ $user->profile_picture != "" ? asset('/uploads/profile/'.$user->profile_picture) : asset('/images/avatar.png') }}"></td></tr>
			<tr><td>{{ _lang('Business Name') }}</td><td>{{ $user->company->business_name }}</td></tr>
			<tr><td>{{ _lang('Admin Name') }}</td><td>{{ $user->name }}</td></tr>
			<tr><td>{{ _lang('Admin Email') }}</td><td>{{ $user->email }}</td></tr>
			<tr><td>{{ _lang('Status') }}</td><td>{!! $user->company->status == 1 ? clean(status(_lang('Active'), 'success')) : clean(status(_lang('In-Active'), 'danger')) !!}</td></tr>
			@if($user->user_type == 'user')
				<tr><td>{{ _lang('Package') }}</td><td>{{ $user->company->package->package_name }}({{ ucwords($user->company->package_type) }})</td></tr>
				<tr><td>{{ _lang('Package Valid To') }}</td><td>{{ date($date_format, strtotime($user->company->valid_to)) }}</td></tr>
		        <tr>
		        	<td>{{ _lang('Membersip Type') }}</td><td>{!! $user->company->membership_type == 'trial' ? clean(status(ucwords($user->company->membership_type), 'danger')) : clean(status(ucwords($user->company->membership_type), 'success')) !!}</td>
		        </tr>
			@endif
	    </table>

	    @if($user->user_type == 'user')
		    <table class="table table-striped">
		    	<tr>
		    		<td colspan="2" class="text-center"><b>{{ _lang('Package Details') }}</b></td>
		    	</tr>
		    	<tr>
		    		<td><b>{{ _lang('Feature') }}</b></td>
		    		<td class="text-center"><b>{{ _lang('Avaialble Limit') }}</b></td>
		    	</tr>
		    	<tr>
		    		<td>{{ _lang('Websites Limit') }}</td>
		    		<td class="text-center">{{ $user->company->websites_limit }}</td>
		    	</tr>
		    	<tr>
		    		<td>{{ _lang('Recurring Transaction') }}</td>
		    		<td class="text-center">{{ ucwords($user->company->recurring_transaction) }}</td>
		    	</tr>
		    	<tr>
		    		<td>{{ _lang('Online Payment') }}</td>
		    		<td class="text-center">{{ ucwords($user->company->online_payment) }}</td>
		    	</tr>
		    </table>
	    @endif
	</div>
  </div>
 </div>
</div>
@endsection